name: Main Branch CD

on:

  push:

    branches:

      - main

jobs:

  terraform:

    runs-on: ubuntu-latest

    environment: Production

    steps:

    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Format
      run: terraform fmt 
      working-directory: environments/prod
      
    - name: Terraform Init
      run: terraform init
      working-directory: environments/prod
      
    - name: Terraform Validate
      run: terraform validate
      working-directory: environments/prod
      
    - name: Terraform Plan
      run: terraform plan
      working-directory: environments/prod

    - name: Apply
      run: terraform apply -auto-approve tfplan
